language: objective-c
before_install:
    - gem install cocoapods
    - brew update
    - brew install xctool
podfile: Example/Podfile
script: xctool -workspace Example/FLUX.xcworkspace -scheme FLUX-Example build test
